### ISSUE TITLE
FEAT: Implement authentication with JWT

### ISSUE THREAD

**Issue by world2222** [Beinus/Web-Server#3]
# Description
* Implement authentication with JWT
<br>

# Todo
- [ ] Implement the authentication logic.
- [ ] Implement the JWT generating logic.
- [ ] Implement the structure as below.

![image](https://github.com/Beinus/Web-Server/assets/52661837/d77a144d-16d7-4602-90f6-9b9f386fec43)
